- name: install cronie package
  yum:
    name: cronie

- name: create supervisor config
  copy:
    src: cron.ini
    dest: /etc/supervisord.d/cron.ini
  register: supervisor

- supervisorctl:
    name: cron
    state: restarted
  when: supervisor.changed
