- name: enable epel repository
  yum:
    name: http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-6.noarch.rpm
    state: present

- name: install cronie package
  yum:
    name: cronie

- name: create supervisor config
  copy:
    src: cron.ini
    dest: /etc/supervisord.d/cron.ini

- name: start cron
  supervisorctl:
    name: crond
    state: present
